export const industrias = {
  "Agroexportación - CCD":
    "Agro-export - CCD",
  "Agroexportación":
    "Agro-export",
  "Industria creciente cuyos productos agrícolas se comercializan globalmente, explicado por el aumento de la población, los ingresos, la aplicación de nuevas tecnologías que amplían fronteras agrícolas, así como por la tendencia creciente en el consumo de productos naturales, frescos y saludables. Los productos de la agroexportación, al transarse en el mercado global, requieren sistemas complejos de transformación o industrialización, logísticos, tarifarios y fitosanitarios.":
    "A growing industry whose agricultural products are sold globally, driven by population growth, rising incomes, new technologies that expand agricultural frontiers, and the growing trend toward natural, fresh and healthy products. Because agro-export products are traded on the global market, they require complex processing or industrialization, logistics, tariff and phytosanitary systems.",
  "Visión estratégica":
    "Strategic Vision",
  "En el Centro para la Competitividad y el Desarrollo (CCD) brindamos asesoría y asesoría técnica para identificar y crear oportunidades agroexportables. Evaluamos el potencial de los productos para ser insertados en la cadena global, nacional y regional, bajo un enfoque integral que considera comercialización, transformación o industrialización, logística y producción, con un enfoque de crecimiento basado en capital, trabajo y productividad total de factores.":
    "At the Center for Competitiveness and Development (CCD), we provide advisory services and technical assistance to identify and create agro-export opportunities. We assess the potential of products to be integrated into the global, national and regional chain, under a comprehensive approach that considers marketing, processing or industrialization, logistics and production, with a growth approach based on capital, labor and total factor productivity.",
  "Nuestros Servicios":
    "Our Services",
  "Planes de agroexportación":
    "Agro-export plans",
  "Estudios de impactos de proyectos agroexportables":
    "Impact studies of agro-export projects",
  "Desarrollo de clusters y microclusters agroexportables":
    "Development of agro-export clusters and microclusters",
  "Evaluación integral de proyectos agroexportables":
    "Comprehensive evaluation of agro-export projects",
  "Agropecuario - CCD":
    "Agriculture & Livestock - CCD",
  "Agropecuario":
    "Agriculture & Livestock",
  "El sector agropecuario está conformado por las actividades agrícolas y pecuarias. La agrícola, realizada principalmente a través del uso de la tierra, produce alimentos para la población y los animales, mientras que el pecuario está conformado por aquellas actividades dedicadas a la crianza, manejo y explotación de animales para la obtención de alimentos y materias primas.":
    "The agriculture and livestock sector comprises crop-farming and livestock activities. Crop farming, carried out mainly through the use of land, produces food for people and animals, while livestock farming comprises the activities dedicated to raising, managing and exploiting animals to obtain food and raw materials.",
  "Las actividades agropecuarias modernas y en proceso de modernización, de alta y baja escala y productividad, coexisten y contribuyen con el desarrollo local, regional y nacional. Con el propósito de maximizar la productividad con innovación tecnológica y sostenibilidad, las actividades agropecuarias modernas se desarrollan mediante sistemas de producción intensivos que integran tecnologías avanzadas con drones, sensores, inteligencia artificial, biotecnología, entre otros. En tanto, las actividades agropecuarias en proceso de modernización, principalmente de micro y pequeña escala, son aquellas que organizan la comercialización, industrialización o transformación, logística y producción en función de labores familiares.":
    "Modern and modernizing agricultural and livestock activities, at both high and low scale and productivity, coexist and contribute to local, regional and national development. To maximize productivity through technological innovation and sustainability, modern agricultural activities are carried out through intensive production systems that integrate advanced technologies such as drones, sensors, artificial intelligence and biotechnology, among others. Meanwhile, agricultural activities in the process of modernization, mainly micro- and small-scale, are those that organize marketing, industrialization or processing, logistics and production around family labor.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) brindamos asistencia técnica para mejorar la productividad agropecuaria, identificando, diseñando e implementando estrategias y actividades con enfoques territoriales y corredores económicos, en función de cadenas de valor de productos que incluyen comercialización, industrialización o transformación, logística y producción agropecuaria. Evaluamos e identificamos oportunidades para potenciar los beneficios y resultados esperados de las intervenciones agropecuarias, principalmente infraestructura y capital humano, promoviendo enfoques integrales con participación pública y privada.":
    "At the Center for Competitiveness and Development (CCD), we provide technical assistance to improve agricultural and livestock productivity, identifying, designing and implementing strategies and activities under territorial and economic-corridor approaches, based on product value chains that include marketing, industrialization or processing, logistics and agricultural production. We assess and identify opportunities to enhance the expected benefits and results of agricultural interventions, mainly in infrastructure and human capital, promoting comprehensive approaches with public and private participation.",
  "Planes de competitividad y productividad agrícola y/o pecuario":
    "Agricultural and/or livestock competitiveness and productivity plans",
  "Estudio y asistencia técnica en proyectos para mejorar la productividad en cadenas de valor de productos agropecuarios":
    "Studies and technical assistance on projects to improve productivity in agricultural and livestock product value chains",
  "Evaluación de proyectos de infraestructura agropecuaria":
    "Evaluation of agricultural infrastructure projects",
  "Fortalecimiento de capacidades a organizaciones agropecuarias para mejorar la productividad de las cadenas de valor de productos":
    "Capacity building for agricultural organizations to improve the productivity of product value chains",
  "Educación - CCD":
    "Education - CCD",
  "Educación":
    "Education",
  "La educación adecuada y de calidad es fundamental en todo proceso de desarrollo sostenible. La educación genera importantes externalidades positivas, principalmente en los factores productivo, social y cultural. En lo productivo dinamiza la actividad económica al crear una masa crítica de trabajadores especializados y capacitados, con habilidades y potencial creciente. La educación superior de calidad impulsa sustancialmente la productividad, los ingresos y los aportes al Estado por tributos. En el factor social, mayor educación genera cohesión, confianza, paz social y desarrollo, contribuye a generar sinergias sociales para ser más productivos y promueve un mayor desarrollo en los niveles individual, familiar, empresarial y estatal. En el factor cultural, la mayor educación contribuye a formar identidades individuales y colectivas, y genera mayores retornos por la experiencia intercultural.":
    "Adequate, high-quality education is essential to any sustainable development process. Education generates significant positive externalities, mainly in the productive, social and cultural dimensions. In the productive dimension, it energizes economic activity by creating a critical mass of skilled and trained workers with growing abilities and potential. High-quality higher education substantially boosts productivity, incomes and tax contributions to the State. In the social dimension, more education generates cohesion, trust, social peace and development, helps create social synergies to be more productive, and promotes greater development at the individual, family, business and state levels. In the cultural dimension, more education helps shape individual and collective identities and generates greater returns from intercultural experience.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) promovemos la educación para el desarrollo y la prosperidad, con el objetivo de generar oportunidades y alta calidad de vida para las personas de circunscripciones comunal, distrital provincial, regional y nacional. Con este propósito, formulamos estudios de preinversión y expedientes técnicos para construir infraestructura educativa básica regular y para educación superior. Evaluamos y formulamos estudios e implementamos proyectos para mejorar servicios educativos, principalmente logros de aprendizaje y educación tecnológica y digital, en alianzas estratégicas con universidades e instituciones lideres en la materia.":
    "At the Center for Competitiveness and Development (CCD), we promote education for development and prosperity, with the aim of creating opportunities and a high quality of life for people at the community, district, provincial, regional and national levels. To this end, we prepare pre-investment studies and technical files for building regular basic and higher education infrastructure. We evaluate and prepare studies and implement projects to improve educational services, mainly learning outcomes and technological and digital education, through strategic alliances with universities and leading institutions in the field.",
  "Estudios de preinversión y expedientes técnicos para la construcción de infraestructura educativa básica regular y superior":
    "Pre-investment studies and technical files for the construction of regular basic and higher education infrastructure",
  "Líneas de base, estudios de preinversión y definitivos y evaluación de proyectos sobre logros de aprendizaje":
    "Baselines, pre-investment and final studies, and evaluation of projects on learning outcomes",
  "Implementación de proyectos de formación digital en la educación básica regular":
    "Implementation of digital training projects in regular basic education",
  "Implementación de proyectos de formación tecnológica en la educación básica regular: computación, electrónica y electricidad":
    "Implementation of technology training projects in regular basic education: computing, electronics and electricity",
  "Evaluación de proyectos ambientales en la educación básica regular":
    "Evaluation of environmental projects in regular basic education",
  "Sistema Financiero - CCD":
    "Financial System - CCD",
  "Sistema Financiero":
    "Financial System",
  "El sistema financiero es el conjunto de instituciones, normas, medios físicos y virtuales y mercados que tienen por objetivo principal canalizar el ahorro de quienes tienen excedente de dinero (ahorradores) hacia quienes necesitan financiamiento (inversores o deudores). Asimismo, el sistema financiero dispone de acuerdos nacionales e internacionales que regulan el flujo de capitales, facilitando la inversión y el financiamiento nacional y global, buscando preservar la estabilidad y la diversificación de riesgos.":
    "The financial system is the set of institutions, rules, physical and virtual channels and markets whose main purpose is to channel the savings of those with surplus funds (savers) to those who need financing (investors or borrowers). The financial system also relies on national and international agreements that regulate capital flows, facilitating national and global investment and financing while seeking to preserve stability and risk diversification.",
  "El sistema financiero contribuye con el desarrollo mediante el rol fundamental de la intermediación financiera, así como por las intervenciones que realiza con proyectos sociales para mejorar la calidad de vida de la población relacionada. Utilizando instrumentos públicos y privados, las instituciones del sistema financiero ejecutan proyectos para mejorar la seguridad, los servicios de agua y alcantarillado, infraestructura vial, entre otras intervenciones sociales para el desarrollo.":
    "The financial system contributes to development through the fundamental role of financial intermediation, as well as through social projects that improve the quality of life of the related population. Using public and private instruments, financial-system institutions carry out projects to improve security, water and sewerage services, road infrastructure and other social interventions for development.",
  "El Centro para la Competitividad y el Desarrollo (CCD) asesora y brinda asistencia técnica en los proyectos sociales que realizan las instituciones financieras, mediante la elaboración de líneas de base, estudios de impactos, estudios de preinversión y definitivos, estudios de evaluación de proyectos, así como en Obras por Impuestos (OxIs) y Asociaciones Público Privadas (APPs). Estas actividades permiten que los proyectos se ejecuten con eficiencia, maximizando los impactos positivos en los beneficiarios.":
    "The Center for Competitiveness and Development (CCD) advises and provides technical assistance on the social projects carried out by financial institutions, through the preparation of baselines, impact studies, pre-investment and final studies and project evaluation studies, as well as on Works-for-Taxes (OxIs) and Public-Private Partnerships (PPPs). These activities allow projects to be executed efficiently, maximizing positive impacts on beneficiaries.",
  "Elaboración de líneas de base, estudios de impactos, estudios de preinversión y definitivos y estudios de evaluación de proyectos":
    "Preparation of baselines, impact studies, pre-investment and final studies, and project evaluation studies",
  "Asesoría y asistencia técnica especializada en la ejecución de proyectos mediante Obras por Impuestos (OxI)":
    "Specialized advisory services and technical assistance for executing projects through Works-for-Taxes (OxI)",
  "Asesoría y asistencia técnica especializada en la ejecución de proyectos de inversión mediante Asociaciones Público Privadas (APPs)":
    "Specialized advisory services and technical assistance for executing investment projects through Public-Private Partnerships (PPPs)",
  "Hidrocarburos - CCD":
    "Hydrocarbons - CCD",
  "Hidrocarburos":
    "Hydrocarbons",
  "El desarrollo de un proyecto en el sector hidrocarburos comprende principalmente el proceso de obtención del lote, la exploración, la construcción y el desarrollo del lote y del pozo, la explotación, el transporte de hidrocarburos, la transformación o refinación en destilados o combustibles y el transporte de los productos comercializables a almacenes, centros productivos e industriales y centros de servicios para abastecer a los consumidores finales. En cada una de estas actividades, las empresas del sector hidrocarburos interactúan y contribuyen con el desarrollo de la población que se encuentran directa e indirectamente relacionada. Dependiendo de cada proyecto en concreto, dicha interacción entre las actividades del proyecto de hidrocarburos y la población puede circunscribirse a escalas multi comunidades, distritos, provincias, regiones y países.":
    "Developing a hydrocarbons project mainly involves obtaining the block, exploration, construction and development of the block and the well, extraction, transportation of hydrocarbons, transformation or refining into distillates or fuels, and transportation of marketable products to warehouses, production and industrial centers and service centers to supply end consumers. In each of these activities, hydrocarbons companies interact with and contribute to the development of the directly and indirectly related population. Depending on the specific project, this interaction between hydrocarbons project activities and the population may span multiple communities, districts, provinces, regions and countries.",
  "En cada una de las actividades del proyecto del sector hidrocarburos, el Centro para la Competitividad y el Desarrollo (CCD) acompaña con asistencia técnica en acciones estratégica y operativas con la población directa e indirectamente relacionada. Planificamos el desarrollo promoviendo la competitividad, creamos instrumentos fiscales para el desarrollo, evaluamos proyectos sociales (improvement / accountability / enligtenment) para encontrar su máximo potencial de impacto y creamos sistemas tecnológicos y digitales para monitorear y acompañar en la ruta hacia el desarrollo.":
    "In each of the activities of a hydrocarbons project, the Center for Competitiveness and Development (CCD) provides technical assistance in strategic and operational actions with the directly and indirectly related population. We plan development by promoting competitiveness, create fiscal instruments for development, evaluate social projects (improvement / accountability / enlightenment) to find their maximum impact potential, and create technological and digital systems to monitor and support the path toward development.",
  "Planes de competitividad y productividad para circunscripciones de proyectos hidrocarburiferos":
    "Competitiveness and productivity plans for the jurisdictions of hydrocarbons projects",
  "Planes de desarrollo concertados regionales y locales":
    "Regional and local concerted development plans",
  "Potenciación del desarrollo con impulso de corredores económicos territoriales":
    "Enhancing development by driving territorial economic corridors",
  "Desarrollo de clusters y microclusters relacionados a los proyectos hidrocarburiferos":
    "Development of clusters and microclusters related to hydrocarbons projects",
  "Fortalecimiento de capacidades a colaboradores y funcionarios de las instituciones públicas y privadas para mejora el sistema de inversión y desarrollo":
    "Capacity building for staff and officials of public and private institutions to improve the investment and development system",
  "Evaluación integral de proyectos de inversión social relacionados a proyectos del sector hidrocarburos":
    "Comprehensive evaluation of social investment projects related to hydrocarbons sector projects",
  "Industrias - CCD":
    "Industries - CCD",
  "Industrias":
    "Industries",
  "El sector agropecuario está conformado por las actividades agrícolas y pecuarias. La agrícola, realizada principalmente a través del uso de la tierra, produce alimentos para la población y los animales.":
    "The agriculture and livestock sector comprises crop-farming and livestock activities. Crop farming, carried out mainly through the use of land, produces food for people and animals.",
  "Es una industria creciente cuyos productos agrícolas se comercializan globalmente, influenciado por el aumento de la población, los ingresos, la aplicación de nuevas tecnologías que amplían fronteras agrícolas.":
    "A growing industry whose agricultural products are sold globally, influenced by population growth, rising incomes and new technologies that expand agricultural frontiers.",
  "La educación adecuada y de calidad es fundamental en todo proceso de desarrollo sostenible. La educación genera importantes externalidades positivas en los factores productivo, social y cultural.":
    "Adequate, high-quality education is essential to any sustainable development process. Education generates significant positive externalities in the productive, social and cultural dimensions.",
  "El desarrollo de un proyecto en el sector hidrocarburos comprenden principalmente el proceso de obtención de los lotes, la exploración, la construcción y el desarrollo de los lotes y pozos hidrocarburiferos.":
    "Developing a hydrocarbons project mainly involves obtaining blocks, exploration, and the construction and development of hydrocarbon blocks and wells.",
  "Infraestructura y Construcción":
    "Infrastructure & Construction",
  "El sector infraestructura y construcción es uno de los pilares del crecimiento económico para mejorar la calidad de vida de la población a niveles global, nacional, regional, provincial, distrital y comunal.":
    "The infrastructure and construction sector is one of the pillars of economic growth to improve the quality of life of the population at the global, national, regional, provincial, district and community levels.",
  "La inteligencia artificial es un conjunto de sistemas tecnológicos (software o hardware) diseñados y elaborados para realizar funciones de aprendizaje profundo (deep learning).":
    "Artificial intelligence is a set of technology systems (software or hardware) designed and built to perform deep learning functions.",
  "Manufactura":
    "Manufacturing",
  "El sector manufacturero mediante métodos, formulas, procesos y actividades se encarga de transformar insumos, materias primas o productos intermedios en bienes terminados o finales para los consumidores.":
    "The manufacturing sector, through methods, formulas, processes and activities, transforms inputs, raw materials or intermediate products into finished goods for consumers.",
  "Minería":
    "Mining",
  "Las etapas de la actividad minera comprenden el proceso de obtención de la concesión minera, la exploración, la construcción y el desarrollo de la mina, la explotación y transformación del recursos minero.":
    "The stages of mining activity include obtaining the mining concession, exploration, mine construction and development, and extraction and processing of mineral resources.",
  "Seguridad Ciudadana":
    "Citizen Security",
  "La seguridad ciudadana es un derecho humano y un bien público que deben ser garantizados por los Estados, en labor conjunta con la sociedad.":
    "Citizen security is a human right and a public good that must be guaranteed by States, working jointly with society.",
  "Sector Público":
    "Public Sector",
  "El sector público está constituido por un conjunto de instituciones y organismos controlados por el Estado a fin de proveer servicios públicos.":
    "The public sector is made up of a set of institutions and bodies controlled by the State in order to provide public services.",
  "Servicios Portuarios":
    "Port Services",
  "Son fundamentales en todo proceso de desarrollo porque permiten mayor comercio internacional, ampliación de mercados y expansión de las ventas de las empresas ubicadas en el país.":
    "They are essential to any development process because they enable greater international trade, market expansion and growth in sales for companies located in the country.",
  "El sistema financiero es el conjunto de instituciones, normas, medios físicos y virtuales y mercados que tienen por objetivo principal canalizar el ahorro de quienes tienen excedente de dinero.":
    "The financial system is the set of institutions, rules, physical and virtual channels and markets whose main purpose is to channel the savings of those with surplus funds.",
  "Tecnología":
    "Technology",
  "La tecnología integra y realiza aplicación práctica del conocimiento para crear dispositivos y servicios que funcionen de manera autónoma y reproducible para resolver problemas y mejorar la calidad de vida de las personas.":
    "Technology integrates and applies knowledge in practice to create devices and services that work autonomously and reproducibly to solve problems and improve people's quality of life.",
  "Infraestructura y Construcción - CCD":
    "Infrastructure & Construction - CCD",
  "El sector infraestructura y construcción es uno de los pilares del crecimiento económico para mejorar la calidad de vida de la población a niveles global, nacional, regional, provincial, distrital y comunal. La infraestructura es el conjunto de estructuras de ingeniería y equipos cuya utilidad y uso se prolonga por un largo periodo. A través del uso de la infraestructura los agentes económicos (familias, empresas y Estado) generan bienes y servicios con fines individuales, sociales y productivos e incrementan los ingresos. La construcción es la creación de infraestructura, principalmente mediante la preparación de terrenos, demoliciones, edificaciones, obras civiles, acondicionamientos, entre otras actividades.":
    "The infrastructure and construction sector is one of the pillars of economic growth to improve the quality of life of the population at the global, national, regional, provincial, district and community levels. Infrastructure is the set of engineering structures and equipment whose usefulness and use extend over a long period. Through the use of infrastructure, economic agents (households, companies and the State) generate goods and services for individual, social and productive purposes and increase their incomes. Construction is the creation of infrastructure, mainly through site preparation, demolition, buildings, civil works, fit-outs and other activities.",
  "La infraestructura es una de las principales fuentes de cierre de brechas económicas y sociales de la población, genera impactos positivos sostenibles en el corto, mediano y largo plazo, reduce la pobreza y genera sociedades prosperas. En el corto plazo dinamiza la economía circunscrita al proyecto de infraestructura, cerrando las brechas de empleos, ingresos y calidad de vida de las personas. La generación de infraestructura es altamente dinamizadora de la economía por la fuerte interrelación con múltiples sectores conexos, relacionados y complementarios. En el mediano y largo plazo se suman impactos positivos como el cierre de brechas en educación, salud, servicios básicos y mayor productividad e ingresos.":
    "Infrastructure is one of the main sources of closing the population's economic and social gaps; it generates sustainable positive impacts in the short, medium and long term, reduces poverty and builds prosperous societies. In the short term, it energizes the economy around the infrastructure project, closing gaps in jobs, incomes and quality of life. Infrastructure generation is a strong driver of the economy because of its close interrelation with multiple connected, related and complementary sectors. In the medium and long term, further positive impacts add up, such as closing gaps in education, health and basic services, and greater productivity and incomes.",
  "En el ámbito individual, familiar y social, una adecuada infraestructura en educación, salud y servicios básicos como saneamiento, energía, telefonía e internet permite a las personas disponer de adecuadas condiciones de productividad e ingresos y calidad de vida. Las condiciones óptimas de salud también están asociadas al acceso a fuentes de energía como electricidad o gas, a la reducción del costo y tiempo en la cocción de alimentos y preservación de los mismos en condiciones frescas, a la conservación de las medicinas, entre otros factores que contribuyen con mejorar la salud y la calidad de vida de la población.":
    "At the individual, family and social level, adequate infrastructure in education, health and basic services such as sanitation, energy, telephony and internet allows people to enjoy adequate conditions of productivity, income and quality of life. Optimal health conditions are also associated with access to energy sources such as electricity or gas, with lower cost and time for cooking food and keeping it fresh, and with the preservation of medicines, among other factors that help improve the population's health and quality of life.",
  "La infraestructura en vías de comunicación en condiciones óptimas de transitabilidad permite que las personas que viven en lugares aislados puedan mejorar el acceso a centros de educación, de salud, de producción y a mercados, lo cual genera acceso a oportunidades de consumo de otros bienes y servicios y empleo, con efectos positivos en el ingreso y en el consumo real. Asimismo, la infraestructura reduce los costos de comercialización, logística, transformación, industrialización y producción, disminuye la depreciación del capital, amplia mercados con rendimientos a escala, mejora la eficiencia de la productividad marginal del capital y del trabajo, consecuentemente favorecen el desempeño de las micros, pequeñas, medianas y grandes empresas. También la existencia de infraestructura adecuada permite la atracción de flujos adicionales de recursos privados, lo que genera la reducción de costos de factores y de transacción en dicho lugar.":
    "Communication infrastructure in optimal, passable condition allows people living in isolated places to improve their access to education, health and production centers and to markets, which opens access to opportunities to consume other goods and services and to employment, with positive effects on income and real consumption. Infrastructure also reduces marketing, logistics, processing, industrialization and production costs, lowers capital depreciation, expands markets with returns to scale, and improves the efficiency of the marginal productivity of capital and labor, consequently benefiting the performance of micro, small, medium and large companies. Adequate infrastructure also attracts additional flows of private resources, which reduces factor and transaction costs in that location.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) elaboramos líneas de base, estudios de impactos, estudios de preinversión y expedientes técnicos para la construcción de infraestructura social enfocada al bienestar y a mejorar la calidad de vida de las personas, principalmente hospitales, escuelas para la educación básica regular y superior, sistemas de agua potable, alcantarillado, energía e infraestructura económica para el desarrollo de la población directa e indirectamente relacionada a empresas de los sectores agropecuario, banca y finanzas, electricidad, hidrocarburos, minería, seguridad, sistemas portuarios, transportes y comunicación como conectividad terrestre, fluvial, aeronáutica y virtual.":
    "At the Center for Competitiveness and Development (CCD), we prepare baselines, impact studies, pre-investment studies and technical files for building social infrastructure aimed at well-being and at improving people's quality of life, mainly hospitals, schools for regular basic and higher education, drinking water and sewerage systems, energy, and economic infrastructure for the development of the population directly and indirectly related to companies in the agriculture and livestock, banking and finance, electricity, hydrocarbons, mining, security, port systems, transport and communication sectors, such as land, river, air and virtual connectivity.",
  "Líneas de base, estudios de impactos, estudios de preinversión y expedientes técnicos para la construcción de infraestructura de servicios básicos y conectividad":
    "Baselines, impact studies, pre-investment studies and technical files for building basic services and connectivity infrastructure",
  "Asesoría y asistencia técnica especializada en la ejecución de proyectos mediante Obras por Impuestos (OxIs)":
    "Specialized advisory services and technical assistance for executing projects through Works-for-Taxes (OxIs)",
  "Asesoría y asistencia técnica especializada en la ejecución de proyectos de inversión mediante Asociaciones Público Privadas (APPs) y Proyectos en Activos (PAs)":
    "Specialized advisory services and technical assistance for executing investment projects through Public-Private Partnerships (PPPs) and Asset Projects (PAs)",
  "Programas de fortalecimiento de capacidades en inversión pública, OxIs, APPs y PAs":
    "Capacity-building programs in public investment, OxIs, PPPs and PAs",
  "Estudios de viabilidad y asistencia técnica para servicios de seguridad tecnológica en centros penitenciarios":
    "Feasibility studies and technical assistance for technological security services in penitentiary facilities",
  "Inteligencia Artificial - CCD":
    "Artificial Intelligence - CCD",
  "La inteligencia artificial es un conjunto de sistemas tecnológicos (software o hardware) diseñados y elaborados para realizar funciones de aprendizaje profundo (deep learning), análisis de grandes volúmenes de datos, razonamiento y percepción, a fin de resolver problemas de manera creativa buscando imitar funcionalidades de la inteligencia humana.":
    "Artificial intelligence is a set of technology systems (software or hardware) designed and built to perform deep learning functions, analysis of large volumes of data, reasoning and perception, in order to solve problems creatively by seeking to imitate the functionalities of human intelligence.",
  "Los sistemas tecnológicos de inteligencia artificial son aplicables a los procesos de desarrollo y competitividad a escalas comunal, local, regional y nacional al tener como objetivos cerrar brechas en las dimensiones del desarrollo o en los determinantes u objetivos priorizados de la competitividad. Para alcanzar estos objetivos se establecen variables e indicadores cuyos comportamientos son explicados con datos que cambian como resultado de la aplicación de políticas y estrategias, programas, proyectos, acciones y actividades públicas y privadas. En todo este ecosistema interactúan agentes económicos como individuos, familias, empresas e instituciones y el Estado, con procesos de aprendizaje e interacciones tipo causa efecto que obedecen a comportamientos económicos, sociales, políticos y culturales en el pasado, en el presente y en el futuro (corto, mediano y largo plazo).":
    "Artificial intelligence technology systems can be applied to development and competitiveness processes at the community, local, regional and national scales, with the objective of closing gaps in the dimensions of development or in the prioritized determinants or objectives of competitiveness. To achieve these objectives, variables and indicators are established whose behavior is explained by data that change as a result of the application of public and private policies and strategies, programs, projects, actions and activities. Across this entire ecosystem, economic agents such as individuals, households, companies and institutions and the State interact, with learning processes and cause-and-effect interactions that follow economic, social, political and cultural behaviors in the past, present and future (short, medium and long term).",
  "En el Centro para la Competitividad y el Desarrollo (CCD) brindamos asistencia técnica especializada y fortalecemos capacidades en inteligencia artificial para actores vinculados a la competitividad y el desarrollo. Desarrollamos soluciones en procesamiento y analítica avanzada de datos, ciencias de datos aplicada, modelos predictivos y prescriptivos, así como en la automatización del análisis situacional y la priorización de inversiones bajo enfoques multicriterio. Asimismo, implementamos sistemas de evaluación automatizados para verificar la consistencia y alineamiento estratégico entre planes, programas, proyectos, acciones, actividades y recursos. Complementamos estos servicios con el diseño y el desarrollo de plataformas inteligentes y sistemas de información institucional orientados a la toma de decisiones basada en evidencia.":
    "At the Center for Competitiveness and Development (CCD), we provide specialized technical assistance and build capacity in artificial intelligence for stakeholders linked to competitiveness and development. We develop solutions in advanced data processing and analytics, applied data science, and predictive and prescriptive models, as well as in the automation of situational analysis and investment prioritization under multi-criteria approaches. We also implement automated evaluation systems to verify the consistency and strategic alignment between plans, programs, projects, actions, activities and resources. We complement these services with the design and development of smart platforms and institutional information systems geared toward evidence-based decision-making.",
  "Fortalecimiento de capacidades en inteligencia artificial para actores vinculados a la competitividad y el desarrollo":
    "Capacity building in artificial intelligence for stakeholders linked to competitiveness and development",
  "Desarrollo de soluciones en procesamiento y analítica avanzada de datos, ciencias de datos aplicada y modelos predictivos y prescriptivos.":
    "Development of solutions in advanced data processing and analytics, applied data science, and predictive and prescriptive models.",
  "Automatización del análisis situacional y la priorización de inversiones bajo enfoques multicriterio":
    "Automation of situational analysis and investment prioritization under multi-criteria approaches",
  "Diseño y desarrollo de plataformas inteligentes y sistemas de información institucional orientados a la toma de decisiones basada en evidencia":
    "Design and development of smart platforms and institutional information systems geared toward evidence-based decision-making",
  "Manufactura - CCD":
    "Manufacturing - CCD",
  "El sector manufacturero mediante métodos, formulas, procesos y actividades se encarga de transformar insumos, materias primas o productos intermedios en bienes terminados o finales para los consumidores o bienes semielaborados demandados por diversos sectores de la economía. La manufactura es un sector altamente diversificado y cuando los participantes alcanzan altos niveles de productividad logran posicionamiento local y global. Esto genera importantes impactos y beneficios como eslabonamientos con múltiples sectores y ramas de la economía, crea y consolida una red importante de proveedores y negocios conexos y relacionados, vincula a los sectores económicos con la academia formativa de profesionales, crea empleos directos, indirectos e inducidos y mayores ingresos, así como mayores pagos de impuestos.":
    "The manufacturing sector, through methods, formulas, processes and activities, transforms inputs, raw materials or intermediate products into finished goods for consumers, or semi-finished goods demanded by various sectors of the economy. Manufacturing is a highly diversified sector, and when its participants reach high levels of productivity they achieve local and global positioning. This generates significant impacts and benefits: linkages with multiple sectors and branches of the economy; the creation and consolidation of an important network of suppliers and related businesses; ties between economic sectors and the academic institutions that train professionals; direct, indirect and induced jobs and higher incomes; and higher tax payments.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) elaboramos paneles de indicadores para evaluar y promover medidas para mejorar la competitividad local y global de industrias específicas de la manufactura. Elaboramos estudios de impactos y beneficios generados por las múltiples industrias manufactureras sobre la economía nacional, regional y local en términos de producción, ingresos, empleos, desarrollo de proveedores e industrias conexas y relacionadas, pago de impuestos y generación de recursos para el desarrollo.":
    "At the Center for Competitiveness and Development (CCD), we prepare indicator dashboards to assess and promote measures to improve the local and global competitiveness of specific manufacturing industries. We prepare studies on the impacts and benefits generated by the various manufacturing industries on the national, regional and local economy in terms of production, income, jobs, development of suppliers and related industries, tax payments and the generation of resources for development.",
  "Elaboración de paneles de indicadores para evaluar y promover medidas para mejorar la competitividad":
    "Preparation of indicator dashboards to assess and promote measures to improve competitiveness",
  "Elaboración de estudios de impactos y beneficios generados por industrias sobre la economía nacional, regional y local":
    "Preparation of studies on the impacts and benefits generated by industries on the national, regional and local economy",
  "Elaboración de estudios sobre crecimiento industrial y crecimiento económico regional":
    "Preparation of studies on industrial growth and regional economic growth",
  "Minería - CCD":
    "Mining - CCD",
  "Las etapas de la actividad minera comprenden principalmente obtención de la concesión minera, exploración, construcción y desarrollo de la mina, explotación y transformación de minerales en productos comercializables y metales, transporte y cierre de minas. En cada una de estas etapas las empresas mineras interactúan y contribuyen con el desarrollo de la población que se encuentran directa e indirectamente relacionada. Dependiendo de cada proyecto minero en concreto, esta interacción de las actividades con la población puede circunscribirse a escalas multi comunales, distritales, provinciales, regionales y países.":
    "The stages of mining activity mainly include obtaining the mining concession, exploration, mine construction and development, extraction and processing of minerals into marketable products and metals, transportation, and mine closure. At each of these stages, mining companies interact with and contribute to the development of the directly and indirectly related population. Depending on the specific mining project, this interaction between activities and the population may span multiple communities, districts, provinces, regions and countries.",
  "En cada una de las etapas de la minería, el Centro para la Competitividad y el Desarrollo (CCD) acompaña con asistencia técnica en acciones estratégica y operativas para el desarrollo sostenido del proyecto minero y de la población relacionada. Planificamos el desarrollo, promovemos la competitividad, creamos instrumentos fiscales para el desarrollo, evaluamos proyectos sociales (improvement, accountability and enligtenment) para encontrar su máximo potencial de impacto y creamos sistemas tecnológicos y digitales para monitorear y acompañar en la ruta hacia el desarrollo. La experiencia de los profesionales del CCD de más de 25 años en la industria minera, en los ámbitos público y privado, a escalas nacional, regional, local y comunal permite desarrollar metodologías y enfoques de abordaje para el desarrollo sostenido con los actores relacionados a los proyectos mineros.":
    "At each stage of mining, the Center for Competitiveness and Development (CCD) provides technical assistance in strategic and operational actions for the sustained development of the mining project and the related population. We plan development, promote competitiveness, create fiscal instruments for development, evaluate social projects (improvement, accountability and enlightenment) to find their maximum impact potential, and create technological and digital systems to monitor and support the path toward development. The experience of CCD professionals, of more than 25 years in the mining industry, in the public and private spheres, at the national, regional, local and community levels, allows us to develop methodologies and approaches for sustained development with the stakeholders related to mining projects.",
  "Planes de competitividad y productividad para circunscripciones de proyectos mineros":
    "Competitiveness and productivity plans for the jurisdictions of mining projects",
  "Evaluación integral de proyectos de inversión social relacionados a proyectos mineros":
    "Comprehensive evaluation of social investment projects related to mining projects",
  "Fortalecimiento de capacidades a colaboradores y funcionarios de las instituciones públicas y privadas para mejora el sistema se inversión y desarrollo":
    "Capacity building for staff and officials of public and private institutions to improve the investment and development system",
  "Desarrollo de proveedores y fuerza laboral local":
    "Development of suppliers and the local workforce",
  "Desarrollo de clusters y microclusters relacionados a los proyectos mineros":
    "Development of clusters and microclusters related to mining projects",
  "Servicios Portuarios - CCD":
    "Port Services - CCD",
  "Los sistemas portuarios son fundamentales en todo proceso de desarrollo porque permiten la transacción de bienes, mayor comercio internacional, ampliación de mercados y expansión de las ventas de las grandes, medianas, pequeñas y micro empresas ubicadas en el país, región, distrito o comunidad. Esto a su vez genera empleos directos, indirectos e inducidos, así como ingresos para los trabajadores y las familias para mejorar la calidad de vida.":
    "Port systems are essential to any development process because they enable the trade of goods, greater international trade, market expansion and growth in sales for large, medium, small and micro businesses located in the country, region, district or community. This in turn generates direct, indirect and induced jobs, as well as income for workers and families to improve their quality of life.",
  "El Centro para la Competitividad y el Desarrollo (CCD) apoya en identificar acciones estratégicas y operativas para el crecimiento sostenido de las actividades del entorno portuario. Brindamos asistencia técnica en planificación, competitividad y desarrollo de la zona de influencia económica y social del sistema portuario, con un enfoque de corredores económicos territoriales. Evaluamos los beneficios generados por el sistema portuario en la zona de influencia. Fortalecemos capacidades en competitividad y desarrollo a los actores relacionados a los sistemas portuarios, principalmente en proyectos de inversión, sistemas tecnológicos de información para la evaluación, seguimiento y acompañamiento del proceso de prosperidad portuario.":
    "The Center for Competitiveness and Development (CCD) helps identify strategic and operational actions for the sustained growth of activities in the port environment. We provide technical assistance in planning, competitiveness and development of the economic and social area of influence of the port system, with a territorial economic corridor approach. We evaluate the benefits generated by the port system in the area of influence. We build capacity in competitiveness and development among stakeholders related to port systems, mainly in investment projects and technology information systems for the evaluation, monitoring and support of the port prosperity process.",
  "Planes de competitividad y productividad regionales de la zona de influencia portuaria":
    "Regional competitiveness and productivity plans for the port area of influence",
  "Planes de desarrollo concertados regionales y locales de la zona de influencia portuaria":
    "Regional and local concerted development plans for the port area of influence",
  "Desarrollo de corredores económicos territoriales relacionados al sistema portuario":
    "Development of territorial economic corridors related to the port system",
  "Desarrollo de clusters y microclusters relacionados al sistema portuario":
    "Development of clusters and microclusters related to the port system",
  "Fortalecimiento de capacidades para el crecimiento del ecosistema portuario":
    "Capacity building for the growth of the port ecosystem",
  "Evaluación integral de programas y proyectos de inversión para el desarrollo portuario":
    "Comprehensive evaluation of investment programs and projects for port development",
  "Sector Público - CCD":
    "Public Sector - CCD",
  "El sector público está constituido por un conjunto de instituciones y organismos controlados por el Estado a fin de proveer servicios públicos como seguridad, protección de la propiedad, justicia, salud, educación, infraestructura física y blanda (instituciones, marcos legales y capital humano necesarios para que la infraestructura física funcione), así como brindar condiciones de estabilidad económica y promoción de los sectores económicos para el crecimiento sostenido y la generación de prosperidad de la población. Para lograr estos fines, el sector público está organizado bajo un sistema de gobernanza nacional, regional o local que debe garantizar el cumplimiento de la ley, con eficiencia, transparencia y rendición de cuentas.":
    "The public sector is made up of a set of institutions and bodies controlled by the State in order to provide public services such as security, protection of property, justice, health, education, and physical and soft infrastructure (the institutions, legal frameworks and human capital needed for physical infrastructure to work), as well as to provide conditions of economic stability and promote economic sectors for sustained growth and the generation of prosperity for the population. To achieve these goals, the public sector is organized under a national, regional or local governance system that must ensure compliance with the law, with efficiency, transparency and accountability.",
  "Para poder implementar las políticas públicas, el Estado recauda ingresos públicos principalmente a través de los tributos que pagan las personas naturales y jurídicas. Estos ingresos públicos deben ser establecidos por el Estado teniendo en cuenta criterios como eficiencia, neutralidad, simplicidad, transparencia, equidad horizontal y vertical, y competitividad internacional.":
    "To implement public policies, the State collects public revenue mainly through taxes paid by individuals and legal entities. This public revenue must be set by the State taking into account criteria such as efficiency, neutrality, simplicity, transparency, horizontal and vertical equity, and international competitiveness.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) brindamos asesoría y asistencia técnica para el diseño, normatividad, implementación y evaluación de políticas públicas, principalmente sobre desarrollo, competitividad, crecimiento económico, infraestructura, planeamiento, descentralización, desarrollo de corredores económicos territoriales e inversión pública; así como en políticas fiscales vinculadas a ingresos, gastos, financiamiento y endeudamiento público, sostenibilidad fiscal, en la creación de nuevos instrumentos fiscales para el desarrollo, en fondos de desarrollo y en mecanismos aceleradores para el crecimiento sostenido de sectores económicos. Asimismo, diseñamos y apoyamos a funcionarios y colaboradores en la implementación de KPIs para la ganancia de eficiencias en las actividades del sector público, a niveles de gobiernos nacional, regional y local.":
    "At the Center for Competitiveness and Development (CCD), we provide advisory services and technical assistance for the design, regulation, implementation and evaluation of public policies, mainly on development, competitiveness, economic growth, infrastructure, planning, decentralization, development of territorial economic corridors and public investment; as well as on fiscal policies linked to revenue, spending, financing and public borrowing, fiscal sustainability, the creation of new fiscal instruments for development, development funds and accelerating mechanisms for the sustained growth of economic sectors. We also design and support officials and staff in implementing KPIs to gain efficiencies in public-sector activities, at the national, regional and local government levels.",
  "Asesoría, asistencia técnica y fortalecimiento de capacidades en diseño, normatividad e implementación y evaluación de políticas públicas":
    "Advisory services, technical assistance and capacity building in the design, regulation, implementation and evaluation of public policies",
  "Asesoría, asistencia técnica y fortalecimiento de capacidades en políticas fiscales":
    "Advisory services, technical assistance and capacity building in fiscal policy",
  "Creación de nuevos instrumentos fiscales para el desarrollo":
    "Creation of new fiscal instruments for development",
  "Asistencia técnica en fondos de desarrollo: gobernanza, estrategias políticas y técnicas, planeamiento, proyectos de inversión para el desarrollo, socialización y participación de actores":
    "Technical assistance on development funds: governance, policy and technical strategies, planning, investment projects for development, outreach and stakeholder participation",
  "Asesoría en determinantes e impulso del crecimiento económico, competitividad y desarrollo":
    "Advisory services on the determinants and drivers of economic growth, competitiveness and development",
  "Asesoría y asistencia técnica en diseño e implementación de KPIs para funcionarios y colaboradores para ganancia de eficiencias":
    "Advisory services and technical assistance in designing and implementing KPIs for officials and staff to gain efficiencies",
  "Seguridad Ciudadana - CCD":
    "Citizen Security - CCD",
  "La seguridad ciudadana es un derecho humano y un bien público que debe ser garantizado por los Estados, en labor conjunta con la sociedad. El objetivo de la seguridad ciudadana es tener convivencia pacífica que proteja la integridad de las personas naturales y jurídicas, con resguardo de los bienes para realizar actividades económicas, sociales, políticas y culturales en un entorno ordenado, seguro y sostenible.":
    "Citizen security is a human right and a public good that must be guaranteed by States, working jointly with society. The objective of citizen security is peaceful coexistence that protects the integrity of individuals and legal entities, safeguarding property so that economic, social, political and cultural activities can be carried out in an orderly, safe and sustainable environment.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) elaboramos estudios de viabilidad y preinversión, expedientes técnicos, estudios de impactos en el entorno o zona de influencia de la construcción de establecimientos penitenciarios e infraestructura policial, brindamos asistencia técnica en asociaciones público privada y obras por impuestos para la instalación de sistemas tecnológicos y de bloqueo de telecomunicaciones.":
    "At the Center for Competitiveness and Development (CCD), we prepare feasibility and pre-investment studies, technical files and impact studies for the surrounding area or area of influence of the construction of penitentiary facilities and police infrastructure, and we provide technical assistance on public-private partnerships and works-for-taxes for the installation of technology and telecommunications-blocking systems.",
  "Elaboración de estudios de preinversión y definitivos para la construcción de establecimientos penitenciarios e infraestructura policial":
    "Preparation of pre-investment and final studies for the construction of penitentiary facilities and police infrastructure",
  "Evaluación de proyectos de construcción de establecimientos penitenciarios e infraestructura policial":
    "Evaluation of construction projects for penitentiary facilities and police infrastructure",
  "Asistencia técnica en asociaciones público privada y obras por impuestos en sistemas tecnológicos y bloqueo de telecomunicaciones":
    "Technical assistance on public-private partnerships and works-for-taxes for technology and telecommunications-blocking systems",
  "Tecnología - CCD":
    "Technology - CCD",
  "La tecnología integra y realiza aplicación práctica del conocimiento para crear dispositivos y servicios que funcionen de manera autónoma y reproducible para resolver problemas y mejorar la calidad de vida de las personas. Mediante aspectos conceptuales, evidencia empírica, métodos, formulas y herramientas digitales, la tecnología permite crear plataformas informáticas para recopilar, analizar y administrar datos, vincular variables e indicadores en el proceso de cierre de brechas en las dimensiones del desarrollo y en los determinantes de la competitividad. Las plataformas tecnológicas sobre el desarrollo y la competitividad permiten planeamiento, fijar niveles de referencia, identificar medidas públicas y privadas correctivas y eficaces, determinar objetivos y metas, fortalecer capacidades, monitorear y acompañar a actores, supervisar avances, evaluar efectos y beneficios, así como comunicar para generar confianza.":
    "Technology integrates and applies knowledge in practice to create devices and services that work autonomously and reproducibly to solve problems and improve people's quality of life. Through conceptual frameworks, empirical evidence, methods, formulas and digital tools, technology makes it possible to create computing platforms to collect, analyze and manage data and to link variables and indicators in the process of closing gaps in the dimensions of development and in the determinants of competitiveness. Technology platforms for development and competitiveness enable planning, setting reference levels, identifying effective corrective public and private measures, defining objectives and targets, building capacity, monitoring and supporting stakeholders, overseeing progress, evaluating effects and benefits, and communicating to build trust.",
  "En el Centro para la Competitividad y el Desarrollo (CCD) desarrollamos técnicas, instrumentos y métodos informáticos y digitales para resolver problemas específicos sobre desarrollo y competitividad para circunscripciones de escalas nacional, regional, local o comunal. Elaboramos Sistemas de Administración del Desarrollo (SAD) para todo tipo de circunscripción o zona de influencia, en versiones ofimática y digitales. Asimismo, creamos sistemas digitales para el fortalecimiento de capacidades para actores clave; y evaluamos, diseñamos e implementamos sistemas virtuales institucionales para promover el desarrollo y la competitividad.":
    "At the Center for Competitiveness and Development (CCD), we develop computing and digital techniques, tools and methods to solve specific problems on development and competitiveness for jurisdictions at the national, regional, local or community scale. We build Development Management Systems (SAD) for every type of jurisdiction or area of influence, in office-software and digital versions. We also create digital systems to build capacity among key stakeholders, and we evaluate, design and implement institutional virtual systems to promote development and competitiveness.",
  "Elaboramos Sistemas de Administración del Desarrollo (SAD)":
    "We build Development Management Systems (SAD)",
  "Desarrollamos sistemas digitales para el fortalecimiento de capacidades para actores clave":
    "We develop digital systems to build capacity among key stakeholders",
  "Evaluamos, diseñamos e implementamos sistemas virtuales institucionales para promover el desarrollo y la competitividad":
    "We evaluate, design and implement institutional virtual systems to promote development and competitiveness",
  "Tecnología para la Competitividad y el Desarrollo":
    "Technology for Competitiveness and Development",
};
